export const routerMap = {
  applyProgress: '/account/apply-progress/index',
  goodsSearch: '/pages/goods-search/index',
  brokerageList:'/pages/brokerage-list/index',
  liveList: '/pages/live-list/index',
  personInfo: '/pages/person-info/index',
  changePwd: '/account/change-pwd/index',
  auth: '/account/auth/index',
  apply: '/account/apply/index',
  reg: '/account/register/index',
  mobileLogin: '/account/mobileLogin/index',
  accountLogin: '/account/accountLogin/index',
  agreement: '/account/agreement/index',
  goodList: '/pages/goods-list/index',
  fillInExpress: '/pages/fill-in-express/index',
  orderDetail: '/pages/order-detail/index',
  // 'pages/index/index',
  // 'pages/mine/index',
  // 'pages/detail/index',
  // 'pages/subpage/index',
}
